### ISSUE TITLE
CustomerActivity does not handle null?

### ISSUE THREAD

**Issue by nattanonr** [coad4u4ever/HUAY#3]
I've done goofed with the database when test adding first prize. By done goofed I mean deleted node t20171116 which contain customers at the moment. So I think f**k it, I'll do it live then proceed to delete my prize node too (result in null database).

I try running the app again thinking "well we have UI to add new customer, this should be easy".
When app start it populate first prize node just fine. But when I click(touch) the "addCustomer" button, the app crash trying to load customer list.

**Comment by coad4u4ever** [comment]
stfu

**Comment by coad4u4ever** [comment]
i'm fixing this shit

**Comment by coad4u4ever** [comment]
the issue has been fixed thanks
